version: '3.8'

networks:
  traefik_net:
    driver: bridge

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/users.htpasswd:/etc/traefik/users.htpasswd
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      # Middleware para asegurar que solo localhost acceda al dashboard
      - "traefik.http.routers.traefik.middlewares=allow-local-only"
      - "traefik.http.middlewares.allow-local-only.ipwhitelist.sourcerange=127.0.0.1/32,::1/128"

  api-registro:
    build: ./api-registro
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/registro`)"
      - "traefik.http.routers.api.entrypoints=web"
      # Middleware de autenticación básica
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/users.htpasswd"
      # Middleware para agregar headers
      - "traefik.http.middlewares.add-headers.headers.customrequestheaders.X-Service-ID=api-registro"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  cliente-app1:
    build: ./cliente-app
    environment:
      - SERVICE_ID=app1
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente-app1.rule=PathPrefix(`/cliente/app1`)"
      - "traefik.http.routers.cliente-app1.entrypoints=web"
      # Middleware stripPrefix
      - "traefik.http.routers.cliente-app1.middlewares=strip-app1"
      - "traefik.http.middlewares.strip-app1.stripprefix.prefixes=/cliente/app1"
      # Middleware para agregar headers
      - "traefik.http.middlewares.add-headers-app1.headers.customrequestheaders.X-Service-ID=app1"
      - "traefik.http.services.cliente-app1.loadbalancer.server.port=4000"

  cliente-app2:
    build: ./cliente-app
    environment:
      - SERVICE_ID=app2
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente-app2.rule=PathPrefix(`/cliente/app2`)"
      - "traefik.http.routers.cliente-app2.entrypoints=web"
      # Middleware stripPrefix
      - "traefik.http.routers.cliente-app2.middlewares=strip-app2"
      - "traefik.http.middlewares.strip-app2.stripprefix.prefixes=/cliente/app2"
      # Middleware para agregar headers
      - "traefik.http.middlewares.add-headers-app2.headers.customrequestheaders.X-Service-ID=app2"
      - "traefik.http.services.cliente-app2.loadbalancer.server.port=4000"

  cliente-app3:
    build: ./cliente-app
    environment:
      - SERVICE_ID=app3
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente-app3.rule=PathPrefix(`/cliente/app3`)"
      - "traefik.http.routers.cliente-app3.entrypoints=web"
      # Middleware stripPrefix
      - "traefik.http.routers.cliente-app3.middlewares=strip-app3"
      - "traefik.http.middlewares.strip-app3.stripprefix.prefixes=/cliente/app3"
      # Middleware para agregar headers
      - "traefik.http.middlewares.add-headers-app3.headers.customrequestheaders.X-Service-ID=app3"
      - "traefik.http.services.cliente-app3.loadbalancer.server.port=4000"

  monitor:
    build: ./monitor
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.rule=PathPrefix(`/monitor`)"
      - "traefik.http.routers.monitor.entrypoints=web"
      # Middleware para agregar headers
      - "traefik.http.middlewares.add-headers-monitor.headers.customrequestheaders.X-Service-ID=monitor"
      - "traefik.http.services.monitor.loadbalancer.server.port=5000"