version: '3.8'

networks:
  traefik_net:
    driver: bridge

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/users.htpasswd:/etc/traefik/users.htpasswd
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=allow-local-only"
      - "traefik.http.middlewares.allow-local-only.ipwhitelist.sourcerange=127.0.0.1/32,::1/128"

  reporte:
    build: ./reporte
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/reporte`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/users.htpasswd"
      - "traefik.http.middlewares.add-headers.headers.customrequestheaders.X-Service-ID=reporte"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  cliente-uno:
    build: ./cliente-app
    environment:
      - SERVICE_ID=uno
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente-uno.rule=PathPrefix(`/cliente/uno`)"
      - "traefik.http.routers.cliente-uno.entrypoints=web"
      - "traefik.http.routers.cliente-uno.middlewares=strip-uno"
      - "traefik.http.middlewares.strip-uno.stripprefix.prefixes=/cliente/uno"
      - "traefik.http.middlewares.add-headers-uno.headers.customrequestheaders.X-Service-ID=uno"
      - "traefik.http.services.cliente-uno.loadbalancer.server.port=4000"

  cliente-dos:
    build: ./cliente-app
    environment:
      - SERVICE_ID=dos
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente-dos.rule=PathPrefix(`/cliente/dos`)"
      - "traefik.http.routers.cliente-dos.entrypoints=web"
      - "traefik.http.routers.cliente-dos.middlewares=strip-dos"
      - "traefik.http.middlewares.strip-dos.stripprefix.prefixes=/cliente/dos"
      - "traefik.http.middlewares.add-headers-dos.headers.customrequestheaders.X-Service-ID=dos"
      - "traefik.http.services.cliente-dos.loadbalancer.server.port=4000"

  
  panel:
    build: ./analiticas
    environment:
      - SERVICE_ID=panel
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=PathPrefix(`/panel`)"
      - "traefik.http.routers.panel.entrypoints=web"
      - "traefik.http.middlewares.add-headers-panel.headers.customrequestheaders.X-Service-ID=panel"
      - "traefik.http.middlewares.strip-panel.stripprefix.prefixes=/reporte/panel"
      - "traefik.http.services.panel.loadbalancer.server.port=5000"

  logs:
    build: ./logger-central
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logs.rule=PathPrefix(`/logs`)"
      - "traefik.http.routers.logs.entrypoints=web"
      - "traefik.http.middlewares.strip-logs.stripprefix.prefixes=/logs"
      - "traefik.http.services.logs.loadbalancer.server.port=5000"